ecotoneframework/ecotone-dev

packages/Dbal/src/DbalConnection.php
Remove Symfony indirect deprecation notices in integrations tests:
1x: Method "Doctrine\Persistence\ConnectionRegistry::getDefaultConnectionName()" might add "string" as a native return type declaration in the future. Do the same in implementation "Ecotone\Dbal\DbalConnection" now to avoid errors or add an explicit @return annotation to suppress this message.
1x: Method "Doctrine\Persistence\ConnectionRegistry::getConnection()" might add "object" as a native return type declaration in the future. Do the same in implementation "Ecotone\Dbal\DbalConnection" now to avoid errors or add an explicit @return annotation to suppress this message.
1x: Method "Doctrine\Persistence\ConnectionRegistry::getConnections()" might add "array" as a native return type declaration in the future. Do the same …
=> Add return types for DbalConfiguration class methods

packages/Dbal/src/DocumentStore/DbalDocumentStore.php, packages/Dbal/tests/DocumentStore/DbalDocumentStoreTest.php
fix issue  #37 Document Store / updateDocument / throws DocumentNotFound if the new document is identical to the existing document
=> handle updates to the document store with identical content

composer.json, packages/PdoEventSourcing/composer.json, packages/PdoEventSourcing/src/Config/InboundChannelAdapter/ProjectionEventHandler.php, packages/PdoEventSourcing/src/InMemory/InMemoryProjectionManager.php, packages/PdoEventSourcing/src/ProjectionStatus.php, packages/PdoEventSourcing/src/Prooph/LazyProophProjectionManager.php, packages/PdoEventSourcing/tests/Behat/features/event-sourcing.feature
without being handled separately resetting projection will stop after second run if load limit is set
=> projection status IDLE is for situation when projection awaits for new events

packages/Ecotone/src/Lite/Test/Configuration/MessageCollectorHandler.php, packages/Ecotone/src/Modelling/InMemoryEventSourcedRepository.php, packages/Ecotone/src/Modelling/SaveAggregateService.php, packages/PdoEventSourcing/src/EventSourcingRepository.php, packages/PdoEventSourcing/tests/Integration/EventSourcingRepositoryBuilderTest.php
- wrapping aggregate events with Event resolves issue with MessageId where saved events had different MessageId than one published and in case of having multiple events published, they all had the same MessageId
=> Making use of Event (with metadata)

packages/Ecotone/src/AnnotationFinder/AnnotationResolver/AttributeResolver.php, packages/Ecotone/src/AnnotationFinder/FileSystem/FileSystemAnnotationFinder.php, packages/Ecotone/src/Messaging/Attribute/IsAbstract.php, packages/Ecotone/tests/AnnotationFinder/Fixture/Usage/Attribute/AbstractClass/TestAbstractHandler.php, packages/Ecotone/tests/AnnotationFinder/Fixture/Usage/Attribute/AbstractClass/TestHandler.php, packages/Ecotone/tests/AnnotationFinder/Unit/FileSystemAttributeAnnotationFinderTest.php, packages/Ecotone/tests/Modelling/Fixture/HandlerWithAbstractClass/TestAbstractHandler.php, packages/Ecotone/tests/Modelling/Fixture/HandlerWithAbstractClass/TestCommand.php, packages/Ecotone/tests/Modelling/Fixture/HandlerWithAbstractClass/TestHandler.php, packages/Ecotone/tests/Modelling/Unit/ModellingEcotoneLiteTest.php
In case annotation is put on abstract classes, it's looked up like any other class. 
As abstract classes can't be initialized on their own, they should be skipped, as they're meaningful only in case other class extends them.
This related to #89
=> Do not lookup abstract classes

packages/Symfony/DepedencyInjection/Compiler/EcotoneCompilerPass.php, packages/Symfony/SymfonyBundle/EcotoneSymfonyBundle.php
The actual symfony bundle is dumping the messaging system configuration with absolute path to the cache directory.
In the context of a cache warmup in a different system than the execution system (typically while bundling lambdas), the the configuration is incorrect.
This PR fixes this issue by using Symfony parameter interpolation feature
=> Fix Symfony bundle dumping absolute path in cache dir

packages/Symfony/SymfonyBundle/EcotoneSymfonyBundle.php
While linting symfony container I'm getting error: `"Invalid service "expressionEvaluationService": method "Ecotone\Messaging\Handler\SymfonyExpressionEvaluationAdapter::createWithExternalExpressionLanguage()" does not exist."`
In fact, this method is not existing. This PR fixes the issue above.
=> Fix Symfony bundle factory definition for SymfonyExpressionEvaluationAdapter service

packages/Dbal/src/Deduplication/DeduplicationInterceptor.php, packages/Dbal/tests/DbalMessagingTest.php, packages/Dbal/tests/Fixture/DeduplicationCommandHandler/EmailCommandHandler.php, packages/Dbal/tests/Integration/DbalBackedMessageChannelTest.php, packages/Dbal/tests/Integration/Deduplication/DbalDeduplicationModuleTest.php
When first message is failed and postgres driver is used, then rolling back creation of deduplication table creates problems with handling consecutive messages.
=> Handle exception during first handling

config_ci.json, packages/Amqp/tests/Behat/Bootstrap/DomainContext.php, packages/Amqp/tests/Behat/features/modelling.feature, packages/Amqp/tests/Fixture/DistributedDeadLetter/Receiver/TicketServiceMessagingConfiguration.php, packages/Ecotone/src/Messaging/Endpoint/ConsumerInterceptor.php, packages/Ecotone/src/Messaging/Endpoint/Interceptor/ConnectionExceptionRetryInterceptor.php, packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitConsumedMessagesInterceptor.php, packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitExecutionAmountInterceptor.php, packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitMemoryUsageInterceptor.php, packages/Ecotone/src/Messaging/Endpoint/Interceptor/SignalInterceptor.php, packages/Ecotone/src/Messaging/Endpoint/Interceptor/TimeLimitInterceptor.php, packages/config.json
Currently if message was handled with failure it was not counted as handled message, which caused to ignore message consumption limit for the message consumer.
=> Count failure handling as message consumption

packages/Ecotone/src/Messaging/Channel/CombinedMessageChannel.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/AsynchronousModule.php, packages/Ecotone/tests/Modelling/Fixture/Outbox/OutboxWithMultipleChannels.php, packages/Ecotone/tests/Modelling/Unit/ModellingEcotoneLiteTest.php
In order to provide possibility to pass through message from database channel providing outbox to a different channel like RabbitMQ, or SQS this PR provides combined Message Channels.
[Read more](https://docs.ecotone.tech/modelling/error-handling/outbox-pattern)
=> Combined Message Channels

composer.json, packages/Sqs/composer.json
Newest version of aws sdk fails on creating sqs queues. Due to that we need to lock on lower version
=> lock aws sdk version

packages/Symfony/DepedencyInjection/MessagingEntrypointCommand.php
Command options (stopOnFailure, handledMessageLimit, ...) are currently ignored in symfony bundle.
=> fix symfony command options

packages/Ecotone/src/Modelling/Event.php, packages/Ecotone/tests/Modelling/Unit/EventTest.php
this happens when Event is loaded from existing stream and sent to projection
=> message ID should not be overwritten.

packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php
Early return if cached configuration is available.
The impact of this PR can be huge on large codebase, as it avoids loading the attributes from catalog when cache is available.
Example with `package/Ecotone/src` as a catalog I got these results for boostraping Ecotone:
```
before.........................I4 - Mo163.687ms (±4.31%)
after..........................I4 - Mo14.700ms (±2.71%)
```
Now booting Ecotone from cache will be stable (14ms in my case) whatever the size of codebase.
=> perf(Ecotone): avoid unnecessary work on boot when cache is available

packages/Ecotone/src/Lite/PsrContainerReferenceSearchService.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/BasicMessagingModule.php, packages/Laravel/src/EcotoneProvider.php, packages/Symfony/DepedencyInjection/Compiler/EcotoneCompilerPass.php
Fix for https://github.com/ecotoneframework/ecotone-dev/issues/128
It will make Expression Evaluation Service always available. In case class is missing, it will use stub.
=> Expression evaluation service always available

packages/Ecotone/src/Lite/EcotoneLite.php, packages/Ecotone/src/Lite/Test/FlowTestSupport.php, packages/PdoEventSourcing/tests/EventSourcingMessagingTest.php, packages/PdoEventSourcing/tests/InMemory/EcotoneLiteEventSourcingTest.php, packages/PdoEventSourcing/tests/InMemory/EventSourcedAggregateTestSupportFrameworkTest.php, packages/PdoEventSourcing/tests/InMemory/EventSourcingRepositoryBuilderTest.php, packages/PdoEventSourcing/tests/InMemory/ProjectionMetadataPropagationTest.php, packages/PdoEventSourcing/tests/InMemory/SynchronousEventDrivenSagaTest.php, packages/PdoEventSourcing/tests/InMemory/ValueObjectIdentifierTest.php, packages/PdoEventSourcing/tests/Integration/AggregateAndProjectionTriggerTest.php, packages/PdoEventSourcing/tests/Integration/AsynchronousEventDrivenProjectionTest.php, packages/PdoEventSourcing/tests/Integration/CategoryStreamTest.php, packages/PdoEventSourcing/tests/Integration/CustomEventStreamTest.php, packages/PdoEventSourcing/tests/Integration/EmittingEventsProjectionTest.php, packages/PdoEventSourcing/tests/Integration/FlowTestingTest.php, packages/PdoEventSourcing/tests/Integration/PollingProjectionTest.php, packages/PdoEventSourcing/tests/Integration/ProjectionFromMultipleStreamsTest.php, packages/PdoEventSourcing/tests/Integration/ProjectionWithStateTest.php, packages/PdoEventSourcing/tests/Integration/SnapshotsTest.php, packages/PdoEventSourcing/tests/Integration/SpecificEventStreamTest.php, packages/PdoEventSourcing/tests/Integration/SynchronousEventDrivenProjectionTest.php
Some tests have not run against production Event Store, this PR fixes that. 
Plus introduce possibility to delete event stream in order to run tests against production event store easier.
=> Ensure all integration tests are running against production event store

packages/Ecotone/src/Messaging/Handler/TypeResolver.php, packages/Ecotone/tests/Messaging/Fixture/Handler/ObjectWithConstructorProperties.php, packages/Ecotone/tests/Messaging/Unit/Handler/InterfaceToCallTest.php
This PR will allow to have attributes targeting property on constructor property parameters.
For example with Doctrine, this will throw an error, because `Column` attribute is targeting property:
```php
#[Entity]
#[Aggregate]
class Mission
{
public function __construct(
#[Column, Id, AggregateIdentifier] public Uuid $id,
) {
}
}
```
=> fix: allow property attributes on constructor arguments

packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/MessagingCommands/MessagingBaseCommand.php, packages/Ecotone/src/Messaging/Endpoint/ExecutionPollingMetadata.php, packages/Ecotone/src/Messaging/Endpoint/InterceptedConsumer.php, packages/Ecotone/src/Messaging/Endpoint/Interceptor/FinishWhenNoMessagesInterceptor.php, packages/Ecotone/src/Messaging/Endpoint/PollingMetadata.php, packages/Ecotone/tests/Messaging/Unit/Endpoint/Poller/PollingConsumerBuilderTest.php
Add `--finishWhenNoMessages` option when running asynchronous endpoints. The execution will be stopped when there are no messages to handle
=> Poll consumer while there are messages to consume

packages/Symfony/SymfonyBundle/Messenger/SymfonyAcknowledgementCallback.php, packages/Symfony/SymfonyBundle/Messenger/SymfonyMessageConverter.php, packages/Symfony/SymfonyBundle/Messenger/SymfonyMessengerMessageChannel.php, packages/Symfony/SymfonyBundle/Messenger/SymfonyMessengerMessageChannelBuilder.php, packages/Symfony/tests/phpunit/MessengerIntegrationTest.php
Symfony Messenger when Message can't be sent to failed transport [will lose the Message.](https://github.com/symfony/symfony/issues/36870)
This is not the case when using Ecotone with Messenger Transport. Ecotone will requeue the message in that case.
To ensure all Message duduplications are handled correctly install [Dbal Module](https://github.com/o/-M-DmcwekWzN78BCsTLK/s/-LmAUnBnyZgZuLF2eWLn/~/changes/681/modules/dbal-support).
=> reliable symfony transport

packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/BasicMessagingModule.php
The error was:
`There is problem with configuration. Interface to call Ecotone\\Messaging\\Endpoint\\Interceptor\\FinishWhenNoMessagesInterceptor:postSend was never registered via related interfaces.`
There was no error when failFast was enabled
=> fix error when using --finishWhenNoMessages and when failFast is disabled

packages/Amqp/tests/Integration/AmqpChannelAdapterTest.php, packages/Dbal/tests/Fixture/ORM/AsynchronousEventHandler/NotificationService.php, packages/Dbal/tests/Integration/CollectorModuleTest.php, packages/Ecotone/src/Messaging/Channel/Collector/Config/CollectorModule.php, packages/Ecotone/src/Messaging/Channel/ExceptionalQueueChannel.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/GlobalPollableChannelConfiguration.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/SendRetries/PollableChannelSendRetriesModule.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/SendRetries/RetriesChannelInterceptorBuilder.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/SendRetries/SendRetryChannelInterceptor.php, packages/Ecotone/src/Messaging/Conversion/ObjectToSerialized/SerializingConverter.php, packages/Ecotone/src/Messaging/Conversion/SerializedToObject/DeserializingConverter.php, packages/Ecotone/src/Messaging/Handler/MessageHandlingException.php, packages/Ecotone/src/Messaging/MessagingException.php, packages/Ecotone/tests/Messaging/Unit/Channel/Collector/CollectorModuleTest.php, packages/Ecotone/tests/Messaging/Unit/Channel/PollableChannel/PollableChannelSendRetriesModuleTest.php, packages/Ecotone/tests/Messaging/Unit/Channel/Serialization/PollableChannelSerializationModuleTest.php, packages/Ecotone/tests/Messaging/Unit/Handler/Logger/LoggingServiceTest.php, packages/Ecotone/tests/Messaging/Unit/Handler/Processor/MethodInvokerTest.php, packages/Ecotone/tests/Modelling/Behat/Bootstrap/DomainContext.php
This allows to set up Dead Letter in case our Message fails on sending. This way we can ensure consistency even if unrecoverable issue happen.
=> Allow setting up Dead Letter for Messages failed during sending

composer.json, packages/Dbal/composer.json, packages/Dbal/src/Compatibility/QueryBuilderProxy.php, packages/Dbal/src/DocumentStore/DbalDocumentStore.php, packages/Dbal/src/Recoverability/DbalDeadLetterHandler.php, packages/Dbal/tests/DbalMessagingTestCase.php, packages/Dbal/tests/Fixture/AsynchronousChannelTransaction/OrderService.php, packages/Dbal/tests/Fixture/Transaction/OrderService.php
In order to provide wider support of this library for legacy projects, we should add support for legacy versions of doctrine/dbal library. In particular versions ^2.12.0|^3.0 have a bit different QueryBuilder methods available.
The other small changes are related to accessing the schema manager.
=> Add support of older versions of Doctrine/Dbal library #175

packages/Dbal/src/ObjectManager/ObjectManagerInterceptor.php, packages/Dbal/tests/Fixture/ORM/Person/Person.php, packages/Dbal/tests/Fixture/ORM/Person/PersonWasRenamed.php, packages/Dbal/tests/Fixture/ORM/PersonRepository/RegisterPersonService.php, packages/Dbal/tests/Fixture/ORM/SynchronousEventHandler/SaveMultipleEntitiesHandler.php, packages/Dbal/tests/Integration/ORMTest.php
**Ecotone version(s) affected**: 1.99.0
**Description**  
My tests with synchronous event handlers are failing because of duplicate aggregates primary key when upgrading to 1.99.0 because of the new default configuration clearing the object manager on command bus.
The new default configuration is flushing and clearing the object manager after handling commands. In the case of a synchronous event handler dispatching another command (Command A => Event => Command B), command A will fetch Aggregate A, the event handler will be executed, then Aggregate B will be fetched and saved by Command B, the object manager is cleared, making Aggregate A untracked. When Aggregate A is saved, the object manager think it is a new object and will insert it instead of updating it.
**Possible Solution** …
=> Clearing object manager on command bus in a synchronous flow

docker-compose.yml, packages/Laravel/src/EcotoneProvider.php, packages/Symfony/DepedencyInjection/Compiler/EcotoneCompilerPass.php
Currently symfony and laravel loads test package, which is not meant to run on production.
=> Skip test package in laravel and symfony by default

packages/PdoEventSourcing/src/EventSourcingConfiguration.php, packages/PdoEventSourcing/src/EventSourcingRepository.php, packages/PdoEventSourcing/tests/Fixture/MultiplePersistenceStrategies/Basket.php, packages/PdoEventSourcing/tests/Fixture/MultiplePersistenceStrategies/BasketCreated.php, packages/PdoEventSourcing/tests/Fixture/MultiplePersistenceStrategies/BasketProjection.php, packages/PdoEventSourcing/tests/Fixture/MultiplePersistenceStrategies/EventsConverter.php, packages/PdoEventSourcing/tests/Fixture/MultiplePersistenceStrategies/Order.php, packages/PdoEventSourcing/tests/Fixture/MultiplePersistenceStrategies/OrderCreated.php, packages/PdoEventSourcing/tests/Fixture/MultiplePersistenceStrategies/OrderProjection.php, packages/PdoEventSourcing/tests/Integration/MultiplePersistenceStrategiesTest.php
If custom strategy is not defined, the one default will be used.
resolves #202
=> Allow to define custom persistence strategy per stream.

packages/Symfony/DepedencyInjection/Compiler/CacheCleaner.php, packages/Symfony/DepedencyInjection/Compiler/EcotoneCompilerPass.php
this fixes deprecation message from Symfony and ensures supporting Symfony 7.x in future
=> add `void` return type to `CacheCleaner::clear()` and `EcotoneCompilerPass::process()`

Monorepo/ExampleApp/Lite/app.php
Disable fail fast in ecotone lite benchmark to be comparable with symfony and laravel. [benchmarks](https://github.com/ecotoneframework/ecotone-dev/actions/runs/6348697153)
=> Configure lazy build for ecotone lite benchmarks

.github/workflows/benchmark-pr.yml
Checking if what I am saying is true, presumably closes #224.
=> Explicitly use bash shell in PR stats workflow

packages/Ecotone/src/Messaging/Config/MessagingSystem.php, packages/Ecotone/src/Messaging/Config/NonProxyCombinedGateway.php, packages/Ecotone/src/Messaging/Handler/Gateway/GatewayProxyBuilder.php, packages/Ecotone/tests/Messaging/Unit/Handler/Gateway/GatewayProxyBuilderTest.php
In relation to #223, with current configuration we are always building gateways, even if they are not really used. 
Besides that we may actually want to trigger single method from Gateway Interface, so in reallity booting only specific Gateway for executed method make sense. 
This will provide much of extra performance in testing scenario or HTTP Requests scenarios, where all we do is to send an Command or Query using single method on the Command/Query Bus.
=> Construct gateways only during the first execution and for given method

packages/Amqp/tests/Integration/AmqpMessageChannelTest.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/InMemory/InMemoryAcknowledgeCallback.php, packages/Ecotone/src/Messaging/Config/MessagingSystem.php, packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php, packages/Ecotone/src/Messaging/Endpoint/InterceptedChannelAdapterBuilder.php, packages/Ecotone/src/Messaging/Endpoint/PollingConsumer/PollingConsumerBuilder.php, packages/Ecotone/tests/Messaging/Fixture/Service/CalculatingServiceForAsynchronousScenario.php, packages/Ecotone/tests/Messaging/Unit/Config/MessagingSystemConfigurationTest.php
In case two asynchronous endpoints are run within same process (Which may happen for test cases), it will register same interceptors twice. 
This PR makes building PollingConsumers fully stateless, so this does not rehappen.
Solves #229
=> Fix running two asynchronous endpoints with same process

packages/Ecotone/src/Messaging/Channel/Collector/CollectorSenderInterceptor.php, packages/Ecotone/src/Messaging/Channel/Collector/CollectorStorage.php, packages/Ecotone/src/Messaging/Channel/Collector/Config/CollectorChannelInterceptorBuilder.php, packages/Ecotone/src/Messaging/Channel/Collector/MessageCollectorChannelInterceptor.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/BasicMessagingModule.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/ErrorHandlerModule.php, packages/Ecotone/src/Messaging/Config/Container/ContainerConfig.php, packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php, packages/Ecotone/src/Messaging/Config/ModuleClassList.php, packages/Ecotone/src/Messaging/Endpoint/AcknowledgeConfirmationInterceptor.php, packages/Ecotone/src/Messaging/Handler/Logger/LoggingGateway.php, packages/Ecotone/src/Messaging/Handler/Logger/LoggingService.php, packages/Ecotone/src/Messaging/Handler/Logger/StubLoggingGateway.php, packages/Ecotone/src/Messaging/Handler/Recoverability/ErrorHandler.php, packages/Ecotone/src/Modelling/Config/InstantRetry/InstantRetryInterceptor.php, packages/Ecotone/src/Test/ComponentTestBuilder.php, packages/Ecotone/tests/Messaging/Unit/Handler/ErrorHandler/ErrorHandlerTest.php, packages/OpenTelemetry/src/Configuration/OpenTelemetryModule.php, packages/OpenTelemetry/src/TracerInterceptor.php, packages/OpenTelemetry/src/TracingChannelInterceptor.php, packages/OpenTelemetry/tests/Fixture/AsynchronousFlow/User.php, packages/OpenTelemetry/tests/Fixture/AsynchronousFlow/UserNotifier.php, packages/OpenTelemetry/tests/Fixture/AsynchronousFlow/UserRegistered.php, packages/OpenTelemetry/tests/Integration/TracingTest.php, packages/OpenTelemetry/tests/Integration/TracingTreeTest.php
This starts collecting logs as form of an event. Thanks we will be able to find out more about what actually happening within given trace.
For example sending asynchronous message via Event Bus, firstly collect those instead of sending right away:
=> Improve traces with events

packages/Dbal/src/DbalConnection.php, packages/Dbal/src/DbalReconnectableConnectionFactory.php, packages/Dbal/src/EcotoneManagerRegistryConnectionFactory.php, packages/Dbal/src/ManagerRegistryEmulator.php, packages/Dbal/src/ObjectManager/ObjectManagerInterceptor.php, packages/Dbal/tests/DbalMessagingTestCase.php, packages/Dbal/tests/Fixture/ORM/PersonRepository/ORMPersonRepository.php, packages/Dbal/tests/Integration/ORMTest.php
If you register Connection with Manager Registry, Ecotone will take care of object flush and clearing your object manager. This can be disabled via DbalConfiguration.
As EntityManager may be closed use ManagerRegistry to ensure asynchronous scenarios will always be able to auto-recover (reset and create new EntityManager).
=> Reset manager if closed

packages/Amqp/tests/Fixture/Calendar/Calendar.php, packages/Amqp/tests/Fixture/Calendar/CreateCalendar.php, packages/Amqp/tests/Fixture/Calendar/ScheduleMeeting.php, packages/Amqp/tests/Integration/CallAggregateAsynchronousEndpointTest.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/Serialization/OutboundMessageConverter.php
in some cases message sent to the queue contains serialized aggregate which may exceed the max length AMQP header that can have
=> AMQP header containing serialized aggregate

packages/Symfony/DepedencyInjection/Compiler/CacheWarmer.php
Native return types have been added to it's functions and a new optional buildDir argument to it's warmUp function.
#286
=> Making the symfony cache warmer's type compatible with symfony 7.

composer.json, packages/Laravel/composer.json
Laravel 11 requires a minimum PHP version of 8.2. Tests on 8.0 will not pass.
=> Add support for Laravel 11

packages/Amqp/src/Distribution/AmqpDistributionModule.php, packages/Amqp/tests/Fixture/DistributedEventBus/Publisher/UserService.php, packages/Ecotone/src/Modelling/DistributedBus.php
This adjust the star for distribution event to be used as RabbitMQ hash (#)
=> Distributing events with star

packages/Dbal/src/Recoverability/DbalDeadLetterHandler.php, packages/Dbal/tests/Fixture/DeadLetter/DoubleEventHandler/DoubleEventHandler.php, packages/Dbal/tests/Fixture/DeadLetter/DoubleEventHandler/EcotoneConfiguration.php, packages/Dbal/tests/Fixture/DeadLetter/DoubleEventHandler/ExampleEvent.php, packages/Dbal/tests/Integration/DeadLetterTest.php
There may be a case when two Event Handlers for same Event Message will fail and store Message in Dead Letter.
In this situation second will be blocked from being stored as Message Id will be the same. 
For this situation new Message Id for Dead Letter will be generated, yet Message will preserve it's origin Message In in Message Headers. Therefore replaying dead message will replay it with original Message Id.
=> Handle same Dead Message for different Asynchronous Endpoints

packages/Ecotone/src/Messaging/Conversion/StringToUuid/StringToUuidConverter.php, packages/Ecotone/src/Messaging/Conversion/UuidToString/UuidToStringConverter.php, packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Converter/HeaderConverter.php, packages/Ecotone/src/Messaging/MessageConverter/DefaultHeaderMapper.php, packages/Ecotone/tests/Messaging/Fixture/Handler/HeaderConversion/ConvertedHeaderEndpoint.php, packages/Ecotone/tests/Messaging/Fixture/Handler/HeaderConversion/JsonConverter.php, packages/Ecotone/tests/Messaging/Unit/Handler/HeaderConversionTest.php
This changes the default serialization for Headers to use PHP to PHP with Converters, only if this is not possible conversion will fallback to JSON conversion.
This refers to #309
=> Default php conversion for headers

packages/Dbal/tests/Integration/CollectorModuleTest.php, packages/Ecotone/src/Lite/EcotoneLite.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/AsynchronousModule.php, packages/Ecotone/tests/Lite/Test/MessagingTestSupportFrameworkTest.php
- Speed up async tests with in memory
- Do not Cache Ecotone Lite tests when running inside Ecotone Framework
=> Speed up async in memory tests

packages/Dbal/src/Attribute/DbalParameter.php
Fixes DbalParameter attribute definition which was not correctly dumped in cached container
=> fix dbal parameter definition

packages/Ecotone/src/AnnotationFinder/AnnotationResolver/AttributeResolver.php, packages/Ecotone/src/Messaging/Handler/TypeResolver.php, packages/Ecotone/tests/AnnotationFinder/Fixture/Usage/Attribute/Annotation/ParameterAttribute.php, packages/Ecotone/tests/AnnotationFinder/Fixture/Usage/Attribute/Annotation/PropertyAttribute.php, packages/Ecotone/tests/AnnotationFinder/Fixture/Usage/Attribute/TestingNamespace/Correct/ClassWithPromotedConstructorParameterAttribute.php, packages/Ecotone/tests/AnnotationFinder/Unit/AttributeResolverTest.php, packages/Ecotone/tests/Messaging/Unit/Handler/TypeResolverTest.php
Allow attributes targeting parameters to be used on php>8 promoted properties
Fixes #336 
=> fix attribute resolver on promoted properties

Monorepo/ExampleApp/Lite/app.php, packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php, packages/Ecotone/tests/Messaging/Unit/Config/MessagingSystemConfigurationTest.php
Improve performance of Ecotone configuration phase.
For a medium sized repository using symfony, my cache:clear command went from **22 seconds** (92% of which is ecotone configuration processing)  to **8 seconds**.
This PR delays the endpoint uniqueness check at the compilation phase, so now the check is done only once
- Performance improvement
=> Improve messaging configuration performance

packages/Symfony/composer.json
Remove unneeded and deprecated dependency `laminas/laminas-zendframework-bridge`
=> remove laminas/laminas-zendframework-bridge dependency

.github/workflows/split-testing.yml
Install `laminas/laminas-zendframework-bridge` on `prefer-lowest` for symfony-bundle
- CI
=> ci: fix main ci by installing laminas/laminas-zendframework-bridge

packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/AroundMethodInterceptor.php, packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/AroundMethodInvocation.php
Lower call stack for around interceptors.
Checked on my project, the stack size for calling a command handler in an aggregate went from 72 to 64.
- Optimization
=> Lower stack size of around interceptors

packages/Ecotone/src/Messaging/Config/Container/ContainerBuilder.php, packages/Ecotone/src/Messaging/Config/Container/MessagingContainerBuilder.php, packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php, packages/Ecotone/src/Messaging/Endpoint/PollingConsumer/InterceptedPollingConsumerBuilder.php
Every endpoint has some default PollingMetadata registered in the container even if it is not a polled endpoint.
This PR registers PollingMetadata only for polled endpoints.
On a medium sized Symfony repository, I get a 10% speedup on cache:clear.
- Performance
=> Register polling metadata only for polled endpoints

packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Converter/HeaderBuilder.php, packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Converter/HeaderConverter.php, packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Converter/ParameterDefaultValue.php, packages/Ecotone/src/Modelling/EventSourcingExecutor/AggregateMethodInvoker.php, packages/Ecotone/src/Modelling/EventSourcingExecutor/EnterpriseAggregateMethodInvoker.php, packages/Ecotone/src/Modelling/EventSourcingExecutor/EventSourcingHandlerExecutor.php, packages/Ecotone/src/Modelling/EventSourcingExecutor/OpenCoreAggregateMethodInvoker.php, packages/Ecotone/src/Modelling/EventSourcingHandlerMethod.php
=> Drop unnecessary interfaceToCall in ES aggregate and header converters

packages/PdoEventSourcing/src/ProjectionRunningConfiguration.php
Projection reset is sloooow.
This PR change the default block size before persisting projection state. It is now 1000 (this is the default value of Prooph) so it will send to db the projection state after handling 1000 events.
This change lower by more than 2 the projection reset time in my production tests.
- Performance
=> Speedup event sourced projection reset

packages/Ecotone/src/Lite/Test/FlowTestSupport.php, packages/Ecotone/src/Messaging/Config/Configuration.php, packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php, packages/Ecotone/src/Messaging/Handler/Processor/ChainedMessageProcessorBuilder.php, packages/Ecotone/src/Messaging/Handler/ServiceActivator/MessageProcessorActivatorBuilder.php, packages/Ecotone/src/Modelling/Config/ModellingHandlerModule.php, packages/PdoEventSourcing/tests/Integration/MultiplePersistenceStrategiesTest.php, quickstart-examples/BuildingBlocks/tests/ReadModel/UnapprovedProductListTest.php
In tests, aggregates should be initialized without publishing its events. This helps to initialize complex aggregates without unwanted side-effects which may be subject for testing.
Fixes #364 
- New feature (can introduce breaking change for tests that rely on aggregate initialization side effects)
- This change may require a documentation update which will be propose separately
=> initializing aggregate in tests won't publish its events

_PackageTemplate/LICENSE, _PackageTemplate/README.md, packages/Amqp/LICENSE, packages/Amqp/README.md, packages/Dbal/LICENSE, packages/Dbal/README.md, packages/Ecotone/LICENSE, packages/Ecotone/README.md, packages/Enqueue/LICENSE, packages/Enqueue/README.md, packages/JmsConverter/LICENSE, packages/JmsConverter/README.md, packages/Laravel/LICENSE, packages/Laravel/README.md, packages/LiteApplication/LICENSE, packages/LiteApplication/README.md, packages/OpenTelemetry/LICENSE, packages/OpenTelemetry/README.md, packages/PdoEventSourcing/LICENSE, packages/PdoEventSourcing/README.md, packages/Redis/LICENSE, packages/Redis/README.md, packages/Sqs/LICENSE, packages/Sqs/README.md, packages/Symfony/LICENSE, packages/Symfony/README.md
=> Update package descriptions

Monorepo/CrossModuleTests/Tests/FullAppTestCase.php, packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php
Gateway proxies are registered without their namespace in containers (`Ecotone_Modelling_CommandBus` instead of `Ecotone\__Proxy__\Ecotone_Modelling_CommandBus`). It actually works because the service is built from the `ProxyFactory`, but it can have weird side effects, for instance false alerts from phpstan using the symfony extension.
=> fix gateways fqcn in container definition

packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php
For some reason evaluating PHP class at run time ends up with errors for Laravel. It acts like it would be looking for a file, when there are none. Therefore it ends up failing.
Therefore instead of relying on in fly evaluation, we can dump the file and depend on this.
=> Proxy generation fix

packages/Laravel/tests/Licence/LicenceTest.php, packages/Laravel/tests/Licence/config/ecotone.php, packages/Symfony/DependencyInjection/EcotoneExtension.php, packages/Symfony/tests/phpunit/Licence/LicenceTest.php, packages/Symfony/tests/phpunit/Licence/config/services.php
Allow to use env variables in Ecotone config for Symfony.
It will now work for Symfony, just like it does for Laravel. 
Therefore the environment variables will be resolved during container build and use for preparing Ecotone's configuration.
---
Using environment variables is safe as long as container is build with expected variables. If we will for example build the container, dump it into Docker Image, and the run it in container with different environment variables - only the envs used during build will be used. 
=> Allow to use env variables in Ecotone's Symfony Config

packages/Symfony/DependencyInjection/Compiler/SymfonyConfigurationVariableService.php, packages/Symfony/tests/phpunit/Kernel.php, packages/Symfony/tests/phpunit/SymfonyApplicationTest.php, packages/Symfony/tests/phpunit/config/bundles.php, packages/Symfony/tests/phpunit/config/services.yaml
… parameter values
This fix allows to use ConfigurationVariable with value from env variable for Symfony applications.
Fixes #399
=> Improve SymfonyConfigurationVariableService: resolve env variables in parameters

.github/workflows/split-testing.yml, .github/workflows/test-monorepo.yml, bin/check-licence.php, docker-compose.yml, packages/Ecotone/src/Messaging/Channel/PollableChannel/Serialization/OutboundMessageConverter.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/BasicMessagingModule.php, packages/Ecotone/src/Messaging/Handler/Gateway/NullEntrypointGateway.php, packages/Enqueue/src/EnqueueAcknowledgementCallback.php, packages/Enqueue/src/EnqueueInboundChannelAdapterBuilder.php, packages/Kafka/src/Attribute/KafkaConsumer.php, packages/Kafka/src/Channel/KafkaMessageChannel.php, packages/Kafka/src/Channel/KafkaMessageChannelBuilder.php, packages/Kafka/src/Configuration/KafkaAdmin.php, packages/Kafka/src/Configuration/KafkaBrokerConfiguration.php, packages/Kafka/src/Configuration/KafkaConsumerConfiguration.php, packages/Kafka/src/Configuration/KafkaModule.php, packages/Kafka/src/Configuration/KafkaPublisherConfiguration.php, packages/Kafka/src/Inbound/InboundMessageConverter.php, packages/Kafka/src/Inbound/KafkaAcknowledgementCallback.php, packages/Kafka/src/Inbound/KafkaInboundChannelAdapter.php, packages/Kafka/src/Inbound/KafkaInboundChannelAdapterBuilder.php, packages/Kafka/src/Outbound/KafkaOutboundChannelAdapter.php, packages/Kafka/src/Outbound/KafkaOutboundChannelAdapterBuilder.php, packages/Kafka/tests/Fixture/Handler/ExampleCommand.php, packages/Kafka/tests/Fixture/Handler/ExampleEvent.php, packages/Kafka/tests/Fixture/Handler/MessengerAsyncCommandHandler.php, packages/Kafka/tests/Fixture/Handler/MessengerAsyncEventHandler.php, packages/Kafka/tests/Integration/KafkaChannelAdapterTest.php, packages/Kafka/tests/Integration/KafkaMessageChannelTest.php
This provides Kafka as Message Channel
=> Kafka message channel

packages/Amqp/src/AmqpInboundChannelAdapter.php, packages/Dbal/src/DbalInboundChannelAdapter.php, packages/Enqueue/src/EnqueueInboundChannelAdapter.php, packages/Redis/src/RedisInboundChannelAdapter.php, packages/Sqs/src/SqsInboundChannelAdapter.php
pnctl signals are not executed due to blocking consume, therefore we have to turn it off. 
The minus of this is consume is quicker in the consumption process, and it works with Streams. 
So if this will be fixed in the amqp extension, we can revert that back.
fixes #410
=> Amqp get instead of consume

packages/Ecotone/src/Lite/Test/Configuration/DelayedMessageReleaseHandler.php, packages/Ecotone/src/Lite/Test/Configuration/EcotoneTestSupportModule.php, packages/Ecotone/src/Lite/Test/FlowTestSupport.php, packages/Ecotone/src/Lite/Test/MessagingTestSupport.php, packages/Ecotone/src/Messaging/Attribute/Endpoint/AddHeader.php, packages/Ecotone/src/Messaging/Attribute/Endpoint/Delayed.php, packages/Ecotone/src/Messaging/Attribute/Endpoint/TimeToLive.php, packages/Ecotone/src/Messaging/Channel/DelayableQueueChannel.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/Serialization/OutboundMessageConverter.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/EndpointHeaders/EndpointHeadersInterceptor.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/EndpointHeaders/EndpointHeadersInterceptorModule.php, packages/Ecotone/src/Messaging/Scheduling/EpochBasedClock.php, packages/Ecotone/src/Messaging/Scheduling/StubUTCClock.php, packages/Ecotone/src/Messaging/Scheduling/TimeSpan.php, packages/Ecotone/tests/Lite/Test/MessagingTestSupportFrameworkTest.php, packages/Ecotone/tests/Messaging/Fixture/AddHeaders/AddingMultipleHeaders.php, packages/Ecotone/tests/Messaging/Unit/Channel/DelayableQueueChannelTest.php, packages/Ecotone/tests/Messaging/Unit/Config/Annotation/ModuleConfiguration/EndpointHeadersInterceptorTest.php
This allows to use expression language for delaying and time to live.
=> Allow expression language for delaying and time to live

packages/Amqp/src/Configuration/AmqpModule.php, packages/Amqp/src/Publisher/AmqpMessagePublisherModule.php, packages/Amqp/src/Transaction/AmqpTransactionModule.php, packages/Dbal/src/Configuration/DbalPublisherModule.php, packages/Dbal/src/DbaBusinessMethod/DbaBusinessMethodModule.php, packages/Dbal/src/DbalTransaction/DbalTransactionModule.php, packages/Dbal/src/Deduplication/DeduplicationModule.php, packages/Dbal/src/DocumentStore/DbalDocumentStoreModule.php, packages/Dbal/src/ObjectManager/ObjectManagerModule.php, packages/Dbal/src/Recoverability/DbalDeadLetterModule.php, packages/Ecotone/src/AnnotationFinder/AnnotationFinderFactory.php, packages/Ecotone/src/AnnotationFinder/FileSystem/FileSystemAnnotationFinder.php, packages/Ecotone/src/Lite/EcotoneLite.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/AsynchronousModule.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/NoExternalConfigurationModule.php, packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php, packages/Ecotone/src/Messaging/Config/Module.php, packages/Ecotone/src/Modelling/Config/BusRoutingModule.php, packages/Ecotone/src/Modelling/Config/InstantRetry/InstantRetryModule.php, packages/Ecotone/src/Modelling/Config/ModellingHandlerModule.php, packages/Ecotone/tests/Lite/Test/MessagingTestSupportFrameworkTest.php, packages/Ecotone/tests/Messaging/Fixture/Annotation/ModuleConfiguration/ExampleModuleConfiguration.php, packages/Ecotone/tests/Messaging/Unit/Channel/DynamicChannel/DynamicMessageChannelBuilderTest.php, packages/Laravel/src/EcotoneProvider.php, packages/PdoEventSourcing/src/Config/EventSourcingModule.php, packages/Symfony/DependencyInjection/EcotoneExtension.php
This add automatic registration of in memory channels for testing purposes, if configuration not provided.
This way EcotoneLite tests can become simple to construct and understand.
=> Default test channels

packages/Ecotone/src/Modelling/Config/AggregrateHandlerModule.php, packages/Ecotone/tests/Modelling/Unit/LoadAggregateServiceBuilderTest.php
Storing state stored via business repository, as it was not covered.
=> Storing state stored via business repository

packages/Amqp/src/AmqpOutboundChannelAdapter.php
In relation to #428. To allow Amqp to recover, before retrying.
=> amqp reconnect on sending failure

packages/Ecotone/src/Modelling/AggregateFlow/CallAggregate/CallAggregateResultToMessageConverter.php, packages/Ecotone/src/Modelling/AggregateFlow/CallAggregate/CallAggregateServiceBuilder.php, packages/Ecotone/tests/Modelling/Fixture/AggregateServiceBuilder/EventSourcingAggregateExample.php, packages/Ecotone/tests/Modelling/Unit/EventSourcingAggregateTest.php
This allows to use `void` command handlers for Pure Event Sourcing Aggregates.
=> Allow for side effects only calls for pure es

packages/Amqp/src/AmqpBackedMessageChannelBuilder.php, packages/Amqp/src/AmqpOutboundChannelAdapter.php, packages/Amqp/src/AmqpOutboundChannelAdapterBuilder.php, packages/Amqp/src/AmqpReconnectableConnectionFactory.php, packages/Amqp/src/Transaction/AmqpTransactionInterceptor.php, packages/Amqp/src/Transaction/AmqpTransactionModule.php, packages/Amqp/tests/Configuration/AmqpModuleTest.php, packages/Amqp/tests/Integration/AmqpMessageChannelTest.php, packages/Amqp/tests/Integration/GeneralAmqpTest.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/SendRetries/SendRetryChannelInterceptor.php, packages/Enqueue/src/CachedConnectionFactory.php
- Message is delivered on lost hearbeat, in relation to #428 
- Ensure message is considered sent, when it's stored on RabbitMQ Server side (publisher acks)
=> amqp - message is delivered on lost hearbeat

packages/Dbal/src/Configuration/DbalConfiguration.php, packages/Dbal/src/Deduplication/DeduplicationInterceptor.php, packages/Dbal/src/Deduplication/DeduplicationModule.php, packages/Dbal/tests/Integration/Deduplication/DbalDeduplicationInterceptorTest.php, packages/Dbal/tests/Integration/Deduplication/DbalDeduplicationModuleTest.php, packages/Ecotone/src/Lite/Test/FlowTestSupport.php
Deduplication have run automatically inside the Message Consumer, however deleting record may result in index rebuild which will cause database locks. So when this happened performance of the application was affected, as other places in the system which used deduplication had to wait for lock to finish.
Ecotone now moves the cleaning of deduplication to separate console command, which can be triggered periodically in background. It also introduces batch removal to avoid big volume of data being deleted at once, which could lock table for longer period of time.
=> Deduplication clearing

composer.json, packages/Dbal/src/DocumentStore/DbalDocumentStore.php, packages/Ecotone/src/Messaging/Store/Document/InMemoryDocumentStore.php, packages/Ecotone/src/Modelling/AggregateFlow/LoadAggregate/LoadAggregateServiceBuilder.php, packages/Ecotone/src/Modelling/AggregateFlow/LoadAggregate/LoadEventSourcingAggregateService.php, packages/Ecotone/tests/Modelling/Unit/SaveAggregateServiceBuilderTest.php, packages/JmsConverter/composer.json, packages/JmsConverter/src/JMSConverterBuilder.php, packages/JmsConverter/src/JMSConverterConfiguration.php, packages/JmsConverter/tests/Fixture/ExamplesToConvert/Date/ObjectWithDate.php, packages/JmsConverter/tests/Fixture/ExamplesToConvert/Date/YearMonthDayDateConverter.php, packages/JmsConverter/tests/Fixture/ExamplesToConvert/Enum/Account.php, packages/JmsConverter/tests/Fixture/ExamplesToConvert/Enum/AccountStatus.php, packages/JmsConverter/tests/Fixture/ExamplesToConvert/Enum/AccountStatusConverter.php, packages/JmsConverter/tests/Unit/JMSConverterTest.php
This is to allow more inbuilt functionalities for serialization, and to make event sourcing snapshoting more robust
- Add default JMS handlers, that can be overridden by custom ones
- Add optional default Enum support
- Self heal on unrestorable snapshots and log error
=> Default enum support for jms and handle snapshot failures with grace

packages/Ecotone/src/Modelling/AggregateIdentifierRetrevingService.php, packages/Ecotone/src/Modelling/Config/AggregrateModule.php
This is for backward compatibility, when there are Messages in the queue, which do not contain AggregateMessage::AGGREGATE_ID header. In relation to https://github.com/ecotoneframework/ecotone-dev/pull/454
=> backward compatibility for aggregate id fetching

packages/Ecotone/src/Lite/Test/FlowTestSupport.php, packages/Ecotone/src/Modelling/AggregateFlow/SaveAggregate/AggregateResolver/AggregateResolver.php, packages/Ecotone/src/Modelling/AggregateFlow/SaveAggregate/SaveAggregateService.php, packages/Ecotone/src/Modelling/AggregateFlow/SaveAggregate/SaveAggregateServiceBuilder.php, packages/Ecotone/src/Modelling/AggregateFlow/SaveAggregate/SaveAggregateServiceTemplate.php, packages/Ecotone/src/Modelling/AggregateFlow/SaveAggregate/SaveAggregateTestSetupService.php, packages/Ecotone/src/Modelling/AggregateFlow/SaveAggregate/SaveAggregateTestSetupServiceBuilder.php, packages/Ecotone/src/Modelling/AggregateMessage.php, packages/Ecotone/src/Modelling/Config/AggregrateModule.php, packages/Ecotone/tests/Messaging/Unit/Handler/Processor/InterceptorsOrderingTest.php, packages/Ecotone/tests/Modelling/Fixture/SimplifiedAggregate/SimplifiedAggregate.php, packages/Ecotone/tests/Modelling/Unit/SaveAggregateServiceBuilderTest.php, packages/Ecotone/tests/Modelling/Unit/SaveAggregateTestSetupServiceBuilderTest.php
In case of testing smaller parts or integration with parts of complex ES aggregates it may be redundant to fully setup an aggregate. Calling #[EventSourcingHandler] methods forces that.
Framework should not try to validate correct setup for ES Aggregate because this is never a technical issue.
=> Skip calling event sourcing handler setting initial state for aggregates

packages/Ecotone/src/Modelling/Config/InstantRetry/InstantRetryInterceptor.php, packages/Ecotone/src/Modelling/Config/InstantRetry/InstantRetryModule.php, packages/Ecotone/src/Modelling/Config/InstantRetry/RetryStatusTracker.php, packages/Ecotone/tests/Modelling/Fixture/Retry/RetriedCommandHandler.php, packages/Ecotone/tests/Modelling/Unit/Config/InstantRetry/InstantRetryModuleTest.php
In case Command Bus with enabled retries is executed within context that is already retried, it leads to situation where retries are multipled. 
Besides in case nested retried was executed due to SQL exception then it will not resolve itself as it requires transaction rollback which is done by outer retries.
=> feat: avoid nested retries

packages/Dbal/src/ObjectManager/ManagerRegistryRepository.php, packages/Ecotone/tests/Modelling/Unit/AggregateRepositoriesTest.php
Probable fix for #467 
I did not find a simple way to add a failing test, it should be done with Symfony (for a non emulated ManagerRegistry), Dbal and Event sourcing packages.
#449, by trying to decouple event sourcing from core, removes the majority of "`isEventSourced`" checks. For this reason, a `StandardRepository` implementation should be more precise in its `canHandle` as it can be asked if it can handle event sourced aggregates classes.
=> Fix repository handling

packages/Ecotone/src/Modelling/AggregateFlow/LoadAggregate/LoadAggregateMessageProcessor.php, packages/Ecotone/src/Modelling/MessageHandling/MetadataPropagator/MessageHeadersPropagatorInterceptor.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/AddItemToBasket.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/Basket.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/BasketCreated.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/ItemInventory.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/ItemInventoryCreated.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/ItemReservationCreated.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/ItemReserved.php, packages/Ecotone/tests/Modelling/Fixture/BasketWithReservations/ItemWasAddedToBasket.php, packages/Ecotone/tests/Modelling/Unit/MetadataPropagatingTest.php
when message flow goes outside of aggregate which was called as first, its identifier is always propagated
1. `Item` gets added to `Basket`
2. `Basket` (separated EH) records reservation
3. `ItemInventory` (different aggregate) also records reservation
Problem occurs when loading `ItemInventory` due `Basket` identifier is in use.
=> metadata propagation issue

composer.json, packages/PdoEventSourcing/composer.json, packages/PdoEventSourcing/tests/Integration/GapDetectionInPollingProjectionTest.php, packages/PdoEventSourcing/tests/Integration/GapDetectionInSynchronousProjectionTest.php
due Prooph may change database projections status to `idle` after first cycle when triggered with `keepRunning: false`, non-polling asynchronous database projections should be triggered with `keepRunning: true`
Issue occurs when resetting asynchronous projection. With `keepRunning: false` Prooph will run it once for amount of events defined with `load_count` option and change its status to `idle`. Ecotone checks projection status after first run and runs it again while status remains either as `rebuilding` or `running`.
I made following assumptions:
- InMemory projections are not managed by locks like database projections
- running polling projection makes application responsible for triggering projection
- resetting polling projection acts like it was triggered
- asynchronous, ES …
=> keep projections running

packages/PdoEventSourcing/src/Config/EventSourcingModule.php, packages/PdoEventSourcing/src/Config/InboundChannelAdapter/ProjectionExecutorBuilder.php, packages/PdoEventSourcing/src/Config/ProjectionManagerBuilder.php
Possible performance improvement
LazyProophProjectionManager class was registered multiple times in the container (each action on each projection + each event handler on each projection) while it should be a singleton. This
=> single projection manager service in container

packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/AsynchronousModule.php, packages/Ecotone/src/Modelling/Config/AggregrateModule.php, packages/Ecotone/src/Modelling/Config/Routing/BusRoutingMapBuilder.php, packages/Ecotone/src/Modelling/Config/Routing/RoutingEvent.php, packages/Ecotone/src/Modelling/Config/Routing/RoutingEventHandler.php, packages/Ecotone/src/Modelling/Config/ServiceHandlerModule.php, packages/Ecotone/tests/Messaging/Unit/Handler/Router/BusRoutingMapTest.php, packages/Ecotone/tests/Modelling/Unit/ModellingEcotoneLiteTest.php, packages/PdoEventSourcing/src/Config/EventSourcingModuleRoutingExtension.php
Fix `NamedEvent` resolution for routing aliasing to avoid BC
Routing aliasing introduced in #479 requires `NamedEvent` classes to be added to resolved classes to parse attributes. This was not required before because `NamedEvent` attribute was resolved at runtime.
=> Fix NamedEvent resolution for route aliasing

packages/Dbal/tests/Integration/DbalErrorChannelCommandBusTest.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/ErrorHandlerModule.php, packages/Ecotone/src/Messaging/Handler/Gateway/GatewayInternalProcessor.php, packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Converter/MessageConverter.php, packages/Ecotone/src/Messaging/Handler/Recoverability/DelayedRetryErrorHandler.php, packages/Ecotone/src/Messaging/Handler/Recoverability/ErrorContext.php, packages/Ecotone/src/Messaging/MessageHeaders.php, packages/Ecotone/src/Messaging/Support/ErrorMessage.php, packages/Ecotone/tests/Messaging/Fixture/Handler/FailureHandler/FailureErrorHandler.php, packages/Ecotone/tests/Messaging/Unit/Endpoint/Poller/PollingConsumerBuilderTest.php, packages/Ecotone/tests/Messaging/Unit/Handler/ErrorHandler/ErrorHandlerTest.php
This does allow to handle error messages asynchronously. Previous Error Message was not serializable due to containing of Exception instance itself. Right now ErrorMessage carry exception details in simple serializable format.
=> Allow Error Handler to execute asynchronously

packages/Ecotone/src/Messaging/Handler/Recoverability/ErrorContext.php
Error Context headers could be already stored in Dead Letter, therefore we can't change them without doing B/C. 
Restoring to previous naming.
=> fix: Avoid breaking compatibility for dead letter headers

packages/Ecotone/src/Lite/LazyInMemoryContainer.php, packages/Ecotone/src/Messaging/Channel/PollableChannel/Serialization/OutboundMessageConverter.php, packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Converter/FetchAggregateConverter.php, packages/Ecotone/src/Modelling/Api/Distribution/DistributedServiceMap.php, packages/Ecotone/tests/Messaging/Fixture/Endpoint/ConsumerContinuouslyWorkingService.php, packages/Ecotone/tests/Messaging/Fixture/Handler/Processor/Interceptor/BaseInterceptorExample.php, packages/Ecotone/tests/Messaging/Fixture/Service/CalculatingService.php, packages/Ecotone/tests/Messaging/Unit/Config/MessagingSystemConfigurationTest.php, packages/Ecotone/tests/Messaging/Unit/Handler/Gateway/GatewayProxyBuilderTest.php
With one of recent refactors Distributed Bus DI setup was misconfigured. It was not caught due to In Memory container being used in tests. This is now fixed together with proper In Memory configuration change, to catch such situations in future.
=> [Hotfix] Container loading for Distributed Bus

packages/Ecotone/src/Messaging/Attribute/Poller.php, packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/PollerModule.php, packages/Ecotone/src/Messaging/Endpoint/InterceptedChannelAdapterBuilder.php, packages/Ecotone/src/Messaging/Endpoint/PollingConsumer/InterceptedConsumerRunner.php, packages/Ecotone/src/Messaging/Endpoint/PollingConsumer/InterceptedPollingConsumerBuilder.php, packages/Ecotone/src/Messaging/Endpoint/PollingMetadata.php, packages/Ecotone/tests/Messaging/Fixture/Poller/ExpressionPollerExample.php, packages/Ecotone/tests/Messaging/Fixture/Poller/TimerService.php, packages/Ecotone/tests/Messaging/Unit/Endpoint/PollingConsumer/PollerExpressionTest.php
This provides ability to set up scheduler using expression language:
=> Scheduler with expression language

packages/Ecotone/src/Messaging/Handler/InterfaceParameter.php, packages/Ecotone/src/Modelling/EventSourcingExecutor/EventSourcingHandlerExecutorBuilder.php, packages/Ecotone/tests/Modelling/Fixture/AggregateServiceBuilder/AggregateCreated.php, packages/Ecotone/tests/Modelling/Fixture/AggregateServiceBuilder/AggregateCreatedInterface.php, packages/Ecotone/tests/Modelling/Fixture/AggregateServiceBuilder/EventSourcingAggregateExample.php
According to [documentation](https://docs.ecotone.tech/modelling/command-handling/external-command-handlers/event-handling#subscribe-to-interface-or-abstract-class) it's possible to use Interfaces or Abstract Classes in EventHandlers. However, when I try to use an interface in an EventSourcingHandler, I get the error "<...> is Event Sourcing Handler and should have first parameter as Event Class type hint."
Add `|| interface_exists` check in InterfaceParameter::isObjectTypeHint
=> Allow interfaces in EventSourcingHandler

packages/Ecotone/src/Messaging/Scheduling/Duration.php, packages/Ecotone/src/Projecting/Config/ProjectingConsoleCommands.php, packages/Ecotone/src/Projecting/InMemory/InMemoryProjectionRegistry.php, packages/Ecotone/src/Projecting/ProjectingManager.php, packages/Ecotone/src/Projecting/ProjectionRegistry.php, packages/PdoEventSourcing/src/Projecting/PartitionState/DbalProjectionStateStorage.php, packages/PdoEventSourcing/src/Projecting/StreamSource/EventStoreGlobalStreamSource.php, packages/PdoEventSourcing/src/Projecting/StreamSource/EventStoreGlobalStreamSourceBuilder.php, packages/PdoEventSourcing/src/Projecting/StreamSource/GapAwarePosition.php, packages/PdoEventSourcing/tests/Projecting/GapAwarePositionIntegrationTest.php
- fix DbalProjectionStorage when using manager registry in the container
- Init all projections in one console command: `ecotone:projecting:init --all=true`
- better gap timeout processing for event store stream source (default to 60 seconds timeout)
- don't add gaps if the event timestamp is after gap timeout (avoids adding gaps while backfilling)
=> Projecting improvements 1

packages/Ecotone/src/Messaging/Handler/Type/TypeParser.php, packages/Ecotone/tests/Messaging/Unit/Handler/TypeDescriptorTest.php
`TypeResolver` is not able to parse multiline phpdoc types: it will just take the first line of type.
With the changes introduced by #523 , we can now parse array shapes, which are the most common types that are multiline, and could break some existing code.
For backward compatibility, this PR ignore malformed array shapes and returns a basic 'array' type.
@lifinsky
=> Fix: ignore errors while parsing array shapes

packages/Ecotone/src/Messaging/Conversion/StaticCallConverter.php, packages/Ecotone/tests/Messaging/Unit/Conversion/ReferenceServiceConverterBuilderTest.php
Fixes issue #532 
Allow implicit php type conversion in `StaticCallConverter.php`
=> fix stringable conversion for static converters
