packages/Dbal/tests/Behat/Bootstrap/DomainContext.php
packages/Dbal/tests/Behat/features/modelling.feature
packages/Dbal/tests/Fixture/AsynchronousChannelWithInterceptor/AddMetadataInterceptor.php
packages/Dbal/tests/Fixture/AsynchronousChannelWithInterceptor/ChannelConfiguration.php
packages/Dbal/tests/Fixture/AsynchronousChannelWithInterceptor/OrderService.php
packages/Ecotone/src/Messaging/Channel/DirectChannel.php
packages/Ecotone/src/Messaging/Channel/PublishSubscribeChannel.php
packages/Ecotone/src/Messaging/Channel/SimpleMessageChannelBuilder.php
packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/AsynchronousModule.php
packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php
packages/Ecotone/src/Messaging/Handler/Chain/ChainMessageHandlerBuilder.php
packages/Ecotone/src/Messaging/Handler/InputOutputMessageHandlerBuilder.php
packages/Ecotone/tests/Messaging/Unit/Config/MessagingSystemConfigurationTest.php
packages/Ecotone/tests/Modelling/Behat/Bootstrap/DomainContext.php
packages/Ecotone/tests/Modelling/Behat/features/modelling.feature
packages/Enqueue/src/OutboundMessageConverter.php

Fixes intercepting asynchronous handler.

Fixes intercepting asynchronous handler.

---

packages/PdoEventSourcing/src/Config/EventSourcingModule.php
packages/PdoEventSourcing/src/Config/InboundChannelAdapter/ProjectionEventHandler.php
packages/PdoEventSourcing/src/ProjectionSetupConfiguration.php
packages/PdoEventSourcing/tests/Behat/Bootstrap/DomainContext.php
packages/PdoEventSourcing/tests/Behat/features/event-sourcing.feature
packages/PdoEventSourcing/tests/Fixture/TicketWithPollingProjectionAndOptions/InProgressTicketList.php
packages/PdoEventSourcing/tests/Fixture/TicketWithPollingProjectionAndOptions/ProjectionConfiguration.php

https://docs.ecotone.tech/modelling/event-sourcing/executing-and-managing/running-projections#custom-configuration

Allow to customize projection options

---

packages/Ecotone/src/Messaging/MessageHeaders.php
packages/PdoEventSourcing/src/Config/EventSourcingModule.php
packages/PdoEventSourcing/src/EventSourcingRepository.php

projection setup configuration defined in attribute gets overwritten with default values from projection running configuration

projection setup configuration defined in attribute gets overwritten

---

quickstart-examples/WorkingWithAggregateDirectly/Product.php
quickstart-examples/WorkingWithAggregateDirectly/composer.json
quickstart-examples/WorkingWithAggregateDirectly/run_example.php
quickstart-examples/WorkingWithAggregateDirectly/src/Command/ChangePrice.php
quickstart-examples/WorkingWithAggregateDirectly/src/Command/RegisterProduct.php
quickstart-examples/WorkingWithAggregateDirectly/src/Event/PriceWasChanged.php
quickstart-examples/WorkingWithAggregateDirectly/src/Event/ProductWasRegistered.php
quickstart-examples/WorkingWithAggregateDirectly/src/Infrastructure/EcotoneConfiguration.php
quickstart-examples/WorkingWithAggregateDirectly/src/PriceChange.php
quickstart-examples/WorkingWithAggregateDirectly/src/Product.php
quickstart-examples/WorkingWithAggregateDirectly/src/ProductRepository.php
quickstart-examples/WorkingWithAggregateDirectly/src/ProductService.php
quickstart-examples/composer.json

Example to show how to working with aggregates directly.

Working with aggregates directly

---

.github/workflows/split-testing.yml
.github/workflows/test-monorepo.yml
_PackageTemplate/composer.json
docker-compose.yml
packages/Sqs/composer.json
packages/Sqs/tests/AbstractConnectionTest.php
packages/Sqs/tests/Integration/ConsumerAndPublisherTest.php
packages/Sqs/tests/Integration/SqsBackedMessageChannelTest.php

- Enable tests for SQS
- Enable package split

Enable SQS

---

packages/Ecotone/src/Modelling/Attribute/SagaIdentifier.php
packages/Ecotone/tests/Modelling/Fixture/Saga/OrderFulfilment.php

Add Saga Identifier for not mixing Aggregate and Saga attributes.

Saga identifier attribute

---

_PackageTemplate/tests/Behat/Bootstrap/DomainContext.php
packages/Dbal/src/Recoverability/DbalDeadLetterBuilder.php
packages/Dbal/src/Recoverability/DbalDeadLetterHandler.php
packages/Dbal/tests/Behat/Bootstrap/DomainContext.php
packages/Dbal/tests/DbalMessagingTest.php
packages/Dbal/tests/Integration/Recoverability/DbalDeadLetterTest.php
packages/Ecotone/src/Messaging/Endpoint/ConsumerInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedChannelAdapterBuilder.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedConsumer.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedMessageHandlerConsumerBuilder.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/ConnectionExceptionRetryInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitConsumedMessagesInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitExecutionAmountInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitMemoryUsageInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/SignalInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/TimeLimitInterceptor.php
packages/PdoEventSourcing/tests/EventSourcingMessagingTest.php
quickstart-examples/ErrorHandling/README.md
quickstart-examples/ErrorHandling/composer.json
quickstart-examples/ErrorHandling/run_example.php
quickstart-examples/ErrorHandling/src/Application/OrderService.php
quickstart-examples/ErrorHandling/src/Application/PlaceOrder.php
quickstart-examples/ErrorHandling/src/Domain/Order.php
quickstart-examples/ErrorHandling/src/Domain/OrderRepository.php
quickstart-examples/ErrorHandling/src/Domain/OrderWasPlaced.php
quickstart-examples/ErrorHandling/src/Domain/ShippingService.php
quickstart-examples/ErrorHandling/src/Infrastructure/EcotoneConfiguration.php
quickstart-examples/ErrorHandling/src/Infrastructure/NetworkFailingShippingService.php

Replay message from dlq quickstart example

---

packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/LoggingModule.php
packages/Ecotone/src/Messaging/Endpoint/InboundChannelAdapterEntrypoint.php
packages/Ecotone/src/Messaging/Endpoint/InboundGatewayEntrypoint.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedChannelAdapterBuilder.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedConsumer.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedMessageHandlerConsumerBuilder.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/ConnectionExceptionRetryInterceptor.php
packages/Ecotone/src/Messaging/Handler/Logger/Annotation/LogError.php
packages/Ecotone/src/Messaging/Handler/Logger/LoggingInterceptor.php
packages/Ecotone/src/Messaging/Handler/Logger/LoggingService.php

This PR improves logging:
- It logs every message that is handled asynchronously
- It logs whenever Ecotone retries connection for incoming message

Improve logging

---

packages/Amqp/tests/Integration/AmqpChannelAdapterTest.php
packages/Ecotone/src/Lite/PsrContainerReferenceSearchService.php
packages/Symfony/DepedencyInjection/Compiler/EcotoneCompilerPass.php
packages/Symfony/SymfonyBundle/EcotoneSymfonyBundle.php
packages/Symfony/SymfonyBundle/MessagingSystemFactory.php
packages/Symfony/composer.json

This PR will create the messaging system when injecting the messaging system and not on kernel boot anymore, improving performance when the messaging system is not necessary
Edit : I am waiting for #122 to be validated before continuing

feat(Symfony): boot messaging system on service injection

---

packages/PdoEventSourcing/src/Config/EventSourcingModule.php
packages/PdoEventSourcing/tests/Fixture/LinkingEventsWithoutProjection/EventEmitter.php
packages/PdoEventSourcing/tests/Fixture/LinkingEventsWithoutProjection/NotificationService.php
packages/PdoEventSourcing/tests/Fixture/LinkingEventsWithoutProjection/TicketListUpdated.php
packages/PdoEventSourcing/tests/Fixture/LinkingEventsWithoutProjection/TicketListUpdatedConverter.php
packages/PdoEventSourcing/tests/Integration/LinkingEventsWithoutProjectionTest.php

resolves #194
Impossible to link events from outside of projection

Impossible to link events from outside of projection

---

packages/Ecotone/src/Messaging/Handler/AroundInterceptorHandler.php
packages/Ecotone/src/Messaging/Handler/Processor/HandlerReplyProcessor.php
packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/AroundMethodInvocation.php
packages/Ecotone/src/Messaging/Handler/Processor/WrapWithMessageBuildProcessor.php
packages/Ecotone/src/Messaging/Handler/RequestReplyProducer.php
packages/Ecotone/src/Messaging/Handler/ServiceActivator/ServiceActivatorBuilder.php
packages/Ecotone/src/Modelling/CallAggregateService.php
packages/Ecotone/src/Modelling/CallAggregateServiceBuilder.php
packages/Ecotone/tests/Messaging/Unit/Handler/Processor/MethodInvokerTest.php

It will higher a bit the stack trace depth but seems cleaner, notably in the CallAggregate service.

Refactor around method invocation

---

packages/Symfony/DepedencyInjection/Compiler/CacheWarmer.php
packages/Symfony/DepedencyInjection/Compiler/EcotoneCompilerPass.php

Add hook in to warmup Ecotone's cache on symfony cache:warmup command

Warmup Ecotone cache in symfony

---

packages/Ecotone/src/Messaging/Config/Annotation/ModuleConfiguration/BasicMessagingModule.php
packages/Ecotone/src/Messaging/Endpoint/ConsumerInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedChannelAdapterBuilder.php
packages/Ecotone/src/Messaging/Endpoint/InterceptedMessageHandlerConsumerBuilder.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/ConnectionExceptionRetryInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/FinishWhenNoMessagesInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitConsumedMessagesInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitExecutionAmountInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/LimitMemoryUsageInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/SignalInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/Interceptor/TimeLimitInterceptor.php
packages/Ecotone/src/Messaging/Endpoint/PostSendInterceptor.php

Refactor inbound postSend interceptors

---

packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php
packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php

Properly register cached proxies autoloader + allow readonly cache dir.

---

packages/Symfony/DepedencyInjection/Compiler/EcotoneCompilerPass.php
packages/Symfony/SymfonyBundle/MessagingSystemFactory.php

respect cache configuration in SymfonyBundle's MessagingSystemFactory

---

composer.json
packages/OpenTelemetry/composer.json
packages/OpenTelemetry/src/EcotoneSpanBuilder.php
packages/OpenTelemetry/src/Support/JaegerTracer.php
packages/OpenTelemetry/src/TracerInterceptor.php
packages/OpenTelemetry/src/TracingChannelInterceptor.php
packages/OpenTelemetry/tests/Integration/CorrelatedHeadersPropagationTest.php
packages/OpenTelemetry/tests/Integration/TracingTest.php
packages/OpenTelemetry/tests/Integration/TracingTreeTest.php

More open telemetry tracing scenarios covered

Tracing scenarios and going with official release

---

Monorepo/Benchmark/AsynchronousStackBenchmark.php
Monorepo/Benchmark/BootingEcotoneBenchmark.php
Monorepo/Benchmark/FullAppBenchmarkCase.php
Monorepo/Benchmark/HttpStackBenchmark.php
Monorepo/Benchmark/KernelBootBenchmark.php
Monorepo/CrossModuleTests/Tests/AsynchronousStackTest.php
Monorepo/CrossModuleTests/Tests/FullAppTestCase.php
Monorepo/CrossModuleTests/Tests/HttpStackTest.php
Monorepo/ExampleApp/Common/Domain/Article/Command/ChangeContent.php
Monorepo/ExampleApp/Common/Domain/Article/Command/ChangeTitle.php
Monorepo/ExampleApp/Common/Domain/Article/Command/CreatePublication.php
Monorepo/ExampleApp/Common/Domain/Notification/NotificationSubscriber.php
Monorepo/ExampleApp/Common/Domain/Notification/OrderConfirmationNotification.php
Monorepo/ExampleApp/Common/Domain/Order/Command/PlaceOrder.php
Monorepo/ExampleApp/Common/Domain/Order/Event/OrderWasPlaced.php
Monorepo/ExampleApp/Common/Domain/Order/ShippingAddress.php
Monorepo/ExampleApp/Common/Domain/Product/ProductDetails.php
Monorepo/ExampleApp/Common/Domain/Shipping/ShippingSubscriber.php
Monorepo/ExampleApp/Common/Infrastructure/Messaging/MessageChannelConfiguration.php
Monorepo/ExampleApp/Common/Infrastructure/Output.php
Monorepo/ExampleApp/Lite/app.php
Monorepo/ExampleApp/LiteApplication/app.php

- Clear cache before each test and benchmark
- Add asynchronous endpoints test for different frameworks
- Add benchmarks for the above

Cross framework tests and benchmarks improvements

---

.github/workflows/release.yml
packages/Amqp/composer.json
packages/Dbal/composer.json
packages/Ecotone/composer.json
packages/Enqueue/composer.json
packages/JmsConverter/composer.json
packages/Laravel/composer.json
packages/LiteApplication/composer.json
packages/OpenTelemetry/composer.json
packages/PdoEventSourcing/composer.json
packages/Redis/composer.json
packages/Sqs/composer.json
packages/Symfony/composer.json
quickstart-examples/composer.json

This allows to make releases from different branches via tags

release workflow

---

Monorepo/CrossModuleTests/Tests/Tracing/TracingStackTest.php
Monorepo/ExampleApp/Laravel/app/Providers/AppServiceProvider.php
Monorepo/ExampleApp/Lite/app.php
Monorepo/ExampleApp/LiteApplication/app.php
Monorepo/ExampleApp/Symfony/config/services.php
packages/Ecotone/src/Messaging/MessageHeaders.php
packages/OpenTelemetry/src/Configuration/OpenTelemetryModule.php
packages/OpenTelemetry/src/EcotoneSpanBuilder.php
packages/OpenTelemetry/src/TracerInterceptor.php
packages/OpenTelemetry/src/TracingChannelAdapterBuilder.php
packages/OpenTelemetry/src/TracingChannelInterceptor.php
packages/OpenTelemetry/tests/Integration/CorrelatedHeadersPropagationTest.php
packages/OpenTelemetry/tests/Integration/TracingTest.php
packages/OpenTelemetry/tests/Integration/TracingTreeTest.php

This is pre-final step before we can release with public testing

Test Opentracing with different frameworks

---

packages/Ecotone/src/Messaging/MessageHeaders.php
packages/Ecotone/src/Messaging/Precedence.php
packages/OpenTelemetry/src/Configuration/OpenTelemetryModule.php
packages/OpenTelemetry/src/TracerInterceptor.php
packages/OpenTelemetry/src/TracingChannelInterceptor.php
packages/OpenTelemetry/tests/Integration/TracingTreeTest.php

Tracing improvements

---

docker-compose.yml
packages/Ecotone/src/Messaging/MessageHeaders.php
packages/Ecotone/tests/Messaging/Fixture/Handler/DataReturningService.php
packages/Ecotone/tests/Messaging/Unit/Config/Annotation/ModuleConfiguration/RequiredConsumersModuleTest.php
packages/OpenTelemetry/src/TracerInterceptor.php
packages/OpenTelemetry/src/TracingChannelInterceptor.php

Fixes to work with newest PHP versions locally

Docker image versions

---

docker-compose.yml
packages/OpenTelemetry/src/Configuration/OpenTelemetryModule.php
packages/OpenTelemetry/src/Configuration/TracingConfiguration.php
packages/OpenTelemetry/src/EcotoneForcedTraceFlush.php
packages/OpenTelemetry/tests/Integration/TracingTreeTest.php

- push traces directly to zipkin
- allow force flushing via Ecotone

Tracing improvements 4

---

composer.json
packages/OpenTelemetry/composer.json
quickstart-examples/Microservices/run_example.php

Auto-instrumentation have not yet been adjusted to work with 1.0.0 release

Allow for beta to use auto-instrumentation

---

packages/Amqp/src/Transaction/AmqpTransactionInterceptor.php
packages/Amqp/src/Transaction/AmqpTransactionModule.php
packages/Dbal/src/DbalTransaction/DbalTransactionInterceptor.php
packages/Dbal/src/ObjectManager/ObjectManagerInterceptor.php
packages/Ecotone/src/Messaging/Handler/Recoverability/RetryTemplate.php
packages/OpenTelemetry/src/EcotoneSpanBuilder.php

- Add logging for transactions

Improve tracing

---

composer.json
packages/Ecotone/src/Messaging/Handler/Logger/LoggingGateway.php
packages/Ecotone/src/Messaging/Handler/Logger/LoggingService.php
packages/Ecotone/src/Messaging/Handler/Logger/StubLoggingGateway.php
packages/OpenTelemetry/composer.json

- Add SDK as dependency
- Allow to log Throwable errors

Tracing fixes

---

packages/Dbal/src/DbalReconnectableConnectionFactory.php
packages/Dbal/src/EcotoneManagerRegistryConnectionFactory.php

make use of connection from the configuration

---

packages/PdoEventSourcing/src/ProjectionSetupConfiguration.php
packages/PdoEventSourcing/tests/Integration/GapDetectionTest.php

Add test case for event gap detection in Event Projections

Add test case for event projection gap detection

---

packages/Dbal/src/DbaBusinessMethod/DbaBusinessMethodModule.php
packages/Dbal/src/DbaBusinessMethod/DbalBusinessMethodHandler.php
packages/Dbal/tests/Fixture/DbalBusinessInterface/ParameterDbalTypeConversion.php
packages/Dbal/tests/Integration/DbalBusinessMethod/DbalParameterTypeTest.php

This enable using expression language in SQL statements for Dbal Business Methods.

Allow expression language in SQLs

---

packages/Symfony/SymfonyBundle/Config/SymfonyConnectionModule.php

Handling connection names in new doctrine bundle

Handling connection names in new doctrine bundle

---

packages/Amqp/tests/Fixture/DistributedEventBus/AsynchronousEventHandler/EcotoneConfiguration.php
packages/Amqp/tests/Fixture/DistributedEventBus/AsynchronousEventHandler/TicketNotificationSubscriber.php
packages/Amqp/tests/Fixture/DistributedEventBus/Publisher/UserService.php
packages/Amqp/tests/Fixture/DistributedEventBus/Receiver/TicketRegistered.php
packages/Amqp/tests/Fixture/DistributedEventBus/Receiver/TicketServiceReceiver.php
packages/Amqp/tests/Integration/DistributedEventBusTest.php
packages/Dbal/src/Configuration/DbalConfiguration.php
packages/Dbal/src/ObjectManager/DoctrineORMRepositoryBuilder.php
packages/Dbal/tests/Integration/ORMTest.php
packages/Ecotone/src/Lite/Test/FlowTestSupport.php
packages/Symfony/tests/phpunit/SingleTenant/SingleTenantTest.php
packages/Symfony/tests/phpunit/SingleTenant/src/Application/Customer.php
packages/Symfony/tests/phpunit/SingleTenant/src/Application/External/ExternalRegistrationHappened.php

- improve testing
- add new configuration option for flushing in [doctrine orm repository](https://github.com/ecotoneframework/ecotone-dev/pull/304/files#diff-e7d1860dda695e2711e0906a3273360598fe988f15e50e551cf35308c252072bR183)

Improve testing around distributed bus and doctrine orm

---

README.md

fix php version and packagist downloads  badges

:package: fix php version and packagist downloads  badges

---

README.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #(issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

:package: fix license badge

---

.github/workflows/split-testing.yml
composer.json
packages/Symfony/composer.json

Totally removes laminas-zendframework-bridge issue
Fixes #298 

fix laminas-zend-framework-bridge

---

packages/Ecotone/src/Messaging/Handler/Gateway/Gateway.php
packages/Ecotone/src/Messaging/Handler/Gateway/GatewayInternalHandler.php
packages/Ecotone/src/Messaging/Handler/Gateway/GatewayProxyBuilder.php
packages/Ecotone/src/Messaging/Handler/Gateway/GatewayReplyConverter.php
packages/Ecotone/src/Messaging/Handler/Gateway/MethodCallToMessageConverter.php

Drop unnecessary interface to call references on gateways

---

packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php

order interceptors only once
- Performance

perf: order interceptors only once

---

packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/AroundInterceptorBuilder.php
packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/AroundMethodInterceptor.php
packages/Ecotone/src/Modelling/AggregateFlow/CallAggregate/AggregateMethodInvoker.php
packages/Ecotone/src/Modelling/AggregateFlow/CallAggregate/CallAggregateServiceBuilder.php
packages/Ecotone/src/Modelling/AggregateFlow/CallAggregate/CallEventSourcingAggregateService.php
packages/Ecotone/src/Modelling/AggregateFlow/CallAggregate/CallStateBasedAggregateService.php

Continue #348 with Aggregate handlers
- Performance

Drop unnecessary interface to call references in aggregate handlers

---

packages/Ecotone/src/Messaging/Support/ConcurrencyException.php
packages/Ecotone/src/Modelling/Event.php
packages/PdoEventSourcing/src/EventMapper.php
packages/PdoEventSourcing/src/EventSourcingConfiguration.php
packages/PdoEventSourcing/src/EventStore.php
packages/PdoEventSourcing/src/Prooph/LazyProophEventStore.php
packages/PdoEventSourcing/tests/Integration/EventStreamTest.php

This allows to create Event Stream dynamically for given strategy.
And renames the `single` strategy to `partition` strategy.

Creating given type of Event Stream

---

packages/Ecotone/tests/Messaging/Fixture/InterceptorsOrdering/Gateway.php
packages/Ecotone/tests/Messaging/Fixture/InterceptorsOrdering/InterceptorOrderingAggregate.php
packages/Ecotone/tests/Messaging/Fixture/InterceptorsOrdering/InterceptorOrderingCase.php
packages/Ecotone/tests/Messaging/Fixture/InterceptorsOrdering/OutputHandler.php
packages/Ecotone/tests/Messaging/Unit/Handler/Processor/InterceptorsOrderingTest.php

Intercepting tests with output channnel

Intercepting tests with output channnel

---

packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/AroundInterceptorBuilder.php
packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Pointcut/IncorrectPointcutException.php
packages/Ecotone/src/Messaging/Handler/Processor/MethodInvoker/Pointcut/PointcutParser.php
packages/Ecotone/tests/Messaging/Unit/Handler/Processor/PointcutTest.php
packages/OpenTelemetry/src/Configuration/OpenTelemetryModule.php

Fix opentelemetry pointcut

---

packages/Ecotone/src/Messaging/Endpoint/ExecutionPollingMetadata.php
packages/Ecotone/src/Messaging/Endpoint/PollingMetadata.php
packages/OpenTelemetry/src/TracerInterceptor.php
packages/OpenTelemetry/tests/Fixture/ScheduledHandler/ScheduledHandler.php
packages/OpenTelemetry/tests/Fixture/ScheduledHandler/WorkflowScheduledHandler.php
packages/OpenTelemetry/tests/Integration/TracingTreeTest.php

Add support for tracing scheduled handlers
Fixes #389

Add support for tracing scheduled handlers

---

packages/Amqp/src/AmqpBackedMessageChannelBuilder.php
packages/Amqp/src/Configuration/AmqpModule.php
packages/Amqp/tests/Integration/AmqpMessageChannelTest.php

Add ability to define custom amqp channel for channel

Add ability to define custom amqp channel for channel

---

packages/Ecotone/src/AnnotationFinder/FileSystem/FileSystemAnnotationFinder.php
packages/Ecotone/src/Lite/EcotoneLite.php
packages/Ecotone/tests/Lite/Test/MessagingTestSupportFrameworkTest.php

Invalidate cache when there are any changes to the files under namespaces configuration.

Invalidate cache on file namespaces

---

.github/workflows/split-testing.yml
.github/workflows/test-monorepo.yml
packages/Ecotone/src/Messaging/Endpoint/AcknowledgeConfirmationInterceptor.php
packages/Ecotone/tests/Messaging/Unit/Endpoint/Poller/PollingConsumerBuilderTest.php
packages/Kafka/src/Inbound/KafkaAcknowledgementCallback.php
packages/Kafka/tests/Fixture/Handler/KafkaAsyncCommandHandler.php
packages/Kafka/tests/Fixture/Handler/KafkaAsyncEventHandler.php
packages/Kafka/tests/Integration/KafkaMessageChannelTest.php

Kafka channel requeing

---

packages/Dbal/tests/Integration/CreateAggregateByStateBasedAggregateTest.php
packages/Ecotone/src/Modelling/AggregateFlow/PublishEvents/PublishAggregateEventsService.php
packages/Ecotone/src/Modelling/AggregateFlow/SaveAggregate/SaveAggregateServiceBuilder.php
packages/Ecotone/tests/Modelling/Fixture/EventSourcedAggregateWithInternalEventRecorder/Job.php
packages/Ecotone/tests/Modelling/Unit/SaveAggregateServiceBuilderTest.php
packages/PdoEventSourcing/tests/Fixture/Calendar/CalendarClosed.php
packages/PdoEventSourcing/tests/Fixture/Calendar/CloseCalendar.php
packages/PdoEventSourcing/tests/Fixture/Calendar/EventsConverter.php
packages/PdoEventSourcing/tests/Fixture/Calendar/OpenFreshCalendar.php
packages/PdoEventSourcing/tests/Fixture/CalendarProjection/CalendarProjection.php
packages/PdoEventSourcing/tests/Fixture/EventSourcingCalendarWithInternalRecorder/CalendarWithInternalRecorder.php
packages/PdoEventSourcing/tests/Integration/CreateAggregateByEventSourcingAggregateTest.php

Allow to return new instances of same aggregate

---

packages/Ecotone/src/Lite/EcotoneLite.php

Invalid whole cache on file change in Ecotone Lite

---

packages/Ecotone/src/AnnotationFinder/FileSystem/FileSystemAnnotationFinder.php
packages/Ecotone/src/Lite/EcotoneLite.php
packages/Ecotone/src/Messaging/Config/ServiceCacheConfiguration.php
packages/Laravel/src/EcotoneProvider.php
packages/Laravel/tests/Application/Execution/ApplicationTest.php
packages/LiteApplication/src/EcotoneLiteApplication.php
packages/LiteApplication/src/LiteDIContainer.php
packages/Symfony/DependencyInjection/EcotoneExtension.php

This speeds up local development with Laravel. It dumps and reuse cache as long as files have not changed.

Laravel cache improvements. Speed up local development cache

---

packages/Ecotone/src/Modelling/Api/Distribution/DistributedServiceMap.php
packages/Ecotone/tests/Messaging/Unit/Distributed/DistributedBusWithServiceMapTest.php
packages/Kafka/src/Configuration/KafkaPublisherConfiguration.php

Distributed bus

---

packages/Amqp/tests/Integration/AmqpMessageChannelTest.php
packages/Dbal/tests/Integration/DbalBackedMessageChannelTest.php
packages/Ecotone/src/AnnotationFinder/FileSystem/FileSystemAnnotationFinder.php
packages/Ecotone/src/Messaging/Channel/SimpleMessageChannelBuilder.php
packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php
packages/Ecotone/src/Messaging/Endpoint/AcknowledgeConfirmationInterceptor.php
packages/Ecotone/src/Messaging/Handler/Gateway/GatewayProxyBuilder.php
packages/Ecotone/src/Messaging/MessageHeaders.php
packages/Ecotone/src/Test/StubLogger.php
packages/Ecotone/tests/Lite/EcotoneLiteTest.php
packages/Ecotone/tests/Lite/LiteContainerImplementationTest.php
packages/Ecotone/tests/Messaging/Fixture/Annotation/Interceptor/AroundInterceptorExample.php
packages/Ecotone/tests/Messaging/Fixture/InterceptedBridge/BridgeExampleIncomplete.php
packages/Ecotone/tests/Messaging/Unit/Channel/PollableChannel/PollableChannelSendRetriesModuleTest.php
packages/Ecotone/tests/Messaging/Unit/Config/Annotation/ModuleConfiguration/MethodInterceptorModuleTest.php
packages/Ecotone/tests/Messaging/Unit/Config/MessagingSystemConfigurationTest.php
packages/Ecotone/tests/Messaging/Unit/Endpoint/Poller/PollingConsumerBuilderTest.php
packages/Ecotone/tests/Messaging/Unit/Handler/Logger/LoggingModuleTest.php
packages/Ecotone/tests/Messaging/Unit/MessageHeadersTest.php
packages/Kafka/tests/Integration/KafkaMessageChannelTest.php
packages/Redis/tests/Integration/RedisBackedMessageChannelTest.php
packages/Sqs/tests/Integration/SqsBackedMessageChannelTest.php

General improvements to throw exceptions when missconfiguration happens, and to ensure laravel config with closures is handled correctly.

General improvements

---

packages/Amqp/tests/Fixture/DistributedCommandBus/Interceptor/CustomDistributedBusInterceptor.php
packages/Amqp/tests/Integration/DistributedCommandBusTest.php
packages/Amqp/tests/Integration/DistributedDeadLetterTest.php

To improve test coverage on Amqp Distributed Bus

More amqp tests

---

packages/Ecotone/src/Modelling/AggregateFlow/LoadAggregate/LoadAggregateMessageProcessor.php
packages/Ecotone/src/Modelling/AggregateIdResolver.php
packages/Ecotone/src/Modelling/AggregateIdentifierRetrevingService.php
packages/Ecotone/tests/Modelling/Fixture/Saga/BeforeFinishOrder.php
packages/Ecotone/tests/Modelling/Fixture/Saga/PaymentWasDoneEvent.php
packages/Ecotone/tests/Modelling/Unit/LoadAggregateServiceBuilderTest.php

I have read and agree to the contribution terms outlined in [CONTRIBUTING](https://github.com/ecotoneframework/ecotone-dev/blob/main/CONTRIBUTING.md).

Identifier metadata mapping fails when metadata is set by interceptor

---

packages/Ecotone/tests/Modelling/Fixture/Saga/AsynchronousOrderFulfilment.php
packages/Ecotone/tests/Modelling/Fixture/Saga/PresendFinishOrder.php
packages/Ecotone/tests/Modelling/Unit/LoadAggregateServiceBuilderTest.php

Identifier metadata mapping with async scenarios and presend interceptor

---

packages/Ecotone/src/Messaging/Channel/DynamicChannel/DynamicMessageChannelBuilder.php
packages/Ecotone/tests/Messaging/Unit/Channel/DynamicChannel/DynamicMessageChannelBuilderTest.php

Dynamic channel naming

---

packages/Ecotone/LICENSE
packages/Ecotone/LICENSE-ENTERPRISE

Add details about enterprise licence terms.

Enterprise licence terms

---

packages/Ecotone/src/Modelling/Config/AggregrateModule.php
packages/Ecotone/tests/Modelling/Unit/IdentifierMappingTest.php

Fix command serialization on aggregate handlers

---

.github/workflows/benchmark-pr.yml
packages/Ecotone/src/Modelling/Config/Routing/BusRoutingMap.php
packages/Ecotone/src/Modelling/Config/Routing/BusRoutingMapBuilder.php
packages/Ecotone/tests/Projecting/ProjectingTest.php

Fixes #517 
Before this PR, channels were prioritize globally for all routing keys of a router.
This PR prioritize channels for each routing key, fixing the triggering of projections that has the same target channel for multiiple routing keys that can now have different priorities

Bug projection priority

---

docker-compose.yml

This upgrades docker images to use latest base PHP images and install new sockets extensions (needed for amqp lib)

feat: docker image upgrade
